limit_req_zone $binary_remote_addr zone=api:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=jobs:10m rate=6r/m;
limit_req_zone $server_name zone=globaljobs:10m rate=12r/m;
limit_conn_zone $binary_remote_addr zone=clients:10m;
limit_conn_zone $server_name zone=allclients:10m;
server {
    listen 8080;
    server_name 43.161.223.91;
    include /etc/nginx/quant-api.conf;
}
