const assert=require('node:assert/strict')
const path=require('node:path')
module.exports=async function(page,output) {
  const correlation=page.locator('#correlation')
  const symbols=['600438','600958','601059','601995','688012','688072','688521','001280','002049','300442']
  while(await correlation.locator('.input-row input').count()<10) await correlation.getByRole('button',{name:'添加资产',exact:true}).click()
  for(let i=0;i<10;i++) await correlation.locator('.input-row input').nth(i).fill(symbols[i])
  const calculated=page.waitForResponse(r=>r.url().endsWith('/api/analytics/correlation')&&r.request().method()==='POST')
  await correlation.getByRole('button',{name:'计算相关矩阵',exact:true}).click()
  const matrix=await calculated
  assert.equal(matrix.status(),200)
  assert.equal((await matrix.json()).matrix.length,10)
  await page.waitForFunction(()=>document.querySelector('#correlation .chart').textContent.includes('001280'))
  await correlation.screenshot({path:path.join(output,'ten-assets.png')})
  const backtest=page.locator('#backtest')
  await backtest.locator('select').nth(0).selectOption(['600438','001280'])
  await backtest.locator('select').nth(2).selectOption('index:CSI:000300')
  const accepted=page.waitForResponse(r=>r.url().endsWith('/api/backtests')&&r.request().method()==='POST')
  await backtest.getByRole('button',{name:'提交异步回测',exact:true}).click()
  const response=await accepted
  assert.equal(response.status(),202)
  const jobId=(await response.json()).jobId
  await page.waitForFunction(()=>document.querySelector('#backtest .chart').textContent.includes('基准净值'))
  await page.waitForTimeout(1200)
  await backtest.screenshot({path:path.join(output,'index-benchmark.png')})
  let submissions=0
  page.on('request',r=>{if(r.url().endsWith('/api/backtests')&&r.method()==='POST') submissions++})
  await page.reload()
  await page.getByRole('button',{name:/恢复/}).click()
  await page.waitForFunction(()=>document.querySelector('#backtest .chart').textContent.includes('基准净值'))
  assert.equal(submissions,0)
  await page.waitForTimeout(1200)
  await backtest.screenshot({path:path.join(output,'restored-job.png')})
  const allocation=page.locator('#allocation')
  const generated=page.waitForResponse(r=>r.url().endsWith('/api/allocation/suggestion')&&r.request().method()==='POST')
  await allocation.getByRole('button',{name:'生成模拟建议',exact:true}).click()
  assert.equal((await generated).status(),200)
  await allocation.screenshot({path:path.join(output,'allocation.png')})
  await page.screenshot({path:path.join(output,'overview.png'),fullPage:true})
  await page.route('**/api/data/status',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code:'DATA_NOT_READY',message:'Synthetic unavailable status for browser failure test'})}))
  await page.reload()
  await page.waitForTimeout(800)
  assert.ok(await page.locator('#correlation button.primary').isDisabled())
  assert.ok(await page.locator('#backtest button.primary').isDisabled())
  await page.screenshot({path:path.join(output,'status-unavailable.png')})
  await page.unroute('**/api/data/status')
  await page.reload()
  await page.waitForFunction(()=>document.querySelector('#correlation button.primary') && !document.querySelector('#correlation button.primary').disabled)
  return {tenAssets:true,indexBenchmarkJob:jobId,recoveredWithoutResubmission:true,allocation:true,statusFailureDisabled:true,failureResponse:'explicit synthetic 503 only'}
}
